FROM python:slim

ARG DB_CONNECTION_URL
ARG DOGS_FILE
ARG API_KEY
ARG SENTRY_DNS
ARG SENTRY_ENVIRONMENT
ARG SENTRY_TRACES_SAMPLE_RATE
ARG SENTRY_PROFILES_SAMPLE_RATE

WORKDIR /app
COPY requirements.lock ./
RUN sed -i '/-e file:./d' requirements.lock
RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements.lock

ENV DB_CONNECTION_URL=$DB_CONNECTION_URL
ENV DOGS_FILE=$DOGS_FILE
ENV API_KEY=$API_KEY
ENV SENTRY_DNS=$SENTRY_DNS
ENV SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT
ENV SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE
ENV SENTRY_PROFILES_SAMPLE_RATE=$SENTRY_PROFILES_SAMPLE_RATE

COPY src .

COPY alembic ./alembic
COPY alembic.ini .
RUN alembic upgrade heads || echo "Migration failed or already applied"

EXPOSE 80

CMD ["fastapi", "run", "pawzzle/main.py", "--port", "80"]
