"""Remove image_url column from Dog

Revision ID: 274524f9e064
Revises: 976f1b5d1901
Create Date: 2024-08-10 13:07:22.879007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274524f9e064'
down_revision: Union[str, None] = '976f1b5d1901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('image_url', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
