"""Add img_name to dog model

Revision ID: 976f1b5d1901
Revises: 585b639371ba
Create Date: 2024-08-07 01:09:19.694975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976f1b5d1901'
down_revision: Union[str, None] = '585b639371ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('img_name', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'img_name')
    # ### end Alembic commands ###
