"""Add target_date to Quiz

Revision ID: b40dcb1c92cd
Revises: 274524f9e064
Create Date: 2024-08-11 19:00:25.308841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40dcb1c92cd'
down_revision: Union[str, None] = '274524f9e064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('target_date', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'target_date')
    # ### end Alembic commands ###
