"""Add Rareness

Revision ID: b931fcb7210b
Revises: f13215b30e09
Create Date: 2024-08-28 02:57:01.223674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b931fcb7210b'
down_revision: Union[str, None] = 'f13215b30e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_rareness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common', sa.Integer(), nullable=False),
    sa.Column('uncommon', sa.Integer(), nullable=False),
    sa.Column('rare', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['dog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog_rareness')
    # ### end Alembic commands ###
